services:
  mt5:
    build:
      dockerfile: Dockerfile
    container_name: mt5
    volumes:
      - ./config:/config
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5000:5000"  # MT5 Web Port
      - "5001:5001"  # MT5 API Port
      - "3000:3000"  # VNC Port